security:
  encoders:
    App\Entity\User:
        algorithm:  sha512
  providers:
    user_db:
      entity:
          class: App\Entity\User
          property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      provider: user_db
      form_login:
        login_path: login
        check_path: login

  access_control:
   - { path: ^/admin, roles: ROLE_ADMIN }
   - { path: ^/profile, roles: ROLE_USER }